---
dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - python setup.py -q install

before_script:
  - pip install nose nose-cov pylint

jobs:
  include:
    - stage: lint
      script: pylint motiv/
    - stage: test
      script:
        - nosetests --with-coverage --cover-package=motiv
        - coverage report

stages:
  - lint
  - test
