---
dist: xenial
language: python
python:
  - "3.7"

before_install:
  - pip install nose nose-cov pylint

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - nosetests
  - pylint motiv/
