---
dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - python setup.py -q install

before_script:
  - pip install nose nose-cov pylint

script:
  - nosetests

jobs:
  include:
    - stage: lint
      script: pylint motiv/

stages:
  - lint
